services:
  - type: web
    name: pms-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: mongodbUri
        sync: false
      - key: CLIENT_URL
        value: https://pms-frontend.onrender.com
